language: objective-c
osx_image: xcode9.2
xcode_project: DVR.xcodeproj

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
      env:
       - PLATFORM="iOS Simulator,OS=10.1,name=iPhone 7 Plus"
    - xcode_scheme: DVR-macOS
      xcode_sdk: macosx
      env:
       - PLATFORM="OS X"
    - env:
      - SWIFT_BUILD=true

script: 
  - ./Scripts/travis-build-test.sh
 
